#!/bin/sh -e
# Ma_Sys.ma Inventory 2.0.0 -- PDF Export Facility,
# Copyright (c) 2016, 2020 Ma_Sys.ma.
# For further info send an e-mail to Ma_Sys.ma@web.de.

head -n 4 "$0" | tail -n 2
echo

if [ $# -le 2 ] || [ "$1" = "--help" ]; then
	echo USAGE $0 FROM NUM PDFFILE 1>&2
	exit 1
fi

target="/tmp/ma_inventory_$$"
mkdir "$target"
trap "rm -r \"$target\"" TERM EXIT

java -cp /usr/share/java/okapibarcode-0.2.3.jar:/usr/share/java/ma-inventory-2-barcodegensvg.jar \
	ma.inventory2.BarCodeGenSVG "$1" "$2" "$target"

cp /usr/share/mdvl-ma-inventory-2/masysmaicon_print_sw.pdf "$target"
cp /usr/share/mdvl-ma-inventory-2/barcodes.tex             "$target"
cd "$target"
find . -maxdepth 1 -type f -name 'bc_*.svg' | {
	pids=
	while read -r line; do
		svg2pdf "$line" "${line%.*}.pdf" &
		pids="$pids $!"
	done
	wait $pids || true
}
pdflatex barcodes
pdflatex barcodes

mv barcodes.pdf "$3"
